Repository code-is-evenly-cooked/even-zaro-front, pull requests merged in 2025-06, with the labels that each got.

#60 UI/place-memo-list 장소의 유저 메모리스트 컴포넌트 UI 구현
  public/icons/sampleProfile.svg
  src/components/common/Icons/index.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceUserMemos.tsx
  src/components/map/UserMemoCard.tsx
  src/types/map.ts
Labels: 🎨 UI

#63 Vercel 배포 오류 수정
  src/components/layout/Header/Header.tsx
Labels: 🐛 bug

#64 댓글 수정 UI 생성 및 API 연결
  src/components/post/Comment/CommentAction.tsx
  src/components/post/Comment/CommentInput.tsx
  src/components/post/Comment/CommentList.tsx
  src/components/post/Comment/CommentListItem/CommentEditForm.tsx
  src/components/post/Comment/CommentListItem/index.tsx
  src/components/post/Comment/useCommentList.ts
  src/utils/date.ts
Labels: 🌟 feat

#65 Feat/notification api : 알림목록조회, 개별알림읽기, 전체알림읽기 api 연결
  src/components/notification/NotificationHeader.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationModal.tsx
  src/lib/api/notification.ts
  src/types/notification.ts
Labels: 🌟 feat

#67 홈화면 배너 추가
  package-lock.json
  package.json
  public/banner/banner_dailylife.webp
  public/banner/banner_plz.webp
  public/banner/banner_randombuy.webp
  public/banner/banner_together.webp
  public/banner/banner_zaro.webp
  public/terms/privacy-policy.md
  src/components/Home/BannerSlider.tsx
  src/components/Home/HomeComponent.tsx
  src/components/layout/Header/Header.tsx
Labels: 🐛 bug, 🎨 UI

#68 즐겨찾기 그룹 API 추가와 즐겨찾기 상세 UI 와 API 추가
  src/app/favorite/[groupId]/FavoritePageClient.tsx
  src/app/favorite/[groupId]/page.tsx
  src/components/Profile/BookmarkGroupCard.tsx
  src/components/Profile/BookmarkGroupList.tsx
  src/components/Profile/FavoriteItemCard.tsx
  src/hooks/useBookmarkGroups.ts
  src/hooks/useFavoriteItems.ts
  src/lib/api/bookmark.ts
  src/lib/api/favorite.ts
  src/types/favorite.ts
Labels: 🎨 UI

#69 Feat/notification sse : 안 읽은 알림count 적힌 알림 아이콘 UI, 알림 전역 관리로 refactor, SSE 훅에 수신알림 추가, 알림없을 때 FallbackMessage
  src/components/layout/Header/Header.tsx
  src/components/notification/NotificationButton.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationModal.tsx
  src/hooks/useSse.ts
  src/stores/useNotificationStore.ts
Labels: 🌟 feat, ♻️ refactor, 🎨 UI

#70 fix : Header.tsx import 누락 수정
  src/components/layout/Header/Header.tsx
Labels: 🐛 bug

#71 댓글 수정 API 리팩토링, 댓긇 삭제 API 연결
  src/app/board/[category]/error.tsx
  src/components/post/Comment/CommentAction.tsx
  src/components/post/Comment/CommentInput.tsx
  src/components/post/Comment/useCommentDelete.ts
  src/components/post/Comment/useCommentList.ts
  src/components/post/Comment/useCommentUpdate.ts
  src/lib/api/comment.ts
  src/utils/comment.tsx
Labels: 🌟 feat

#76 답글 UI, 글자 제한, 로딩표시, 시간 포맷팅변경
  package-lock.json
  package.json
  src/components/post/Comment/CommentAction.tsx
  src/components/post/Comment/CommentInput.tsx
  src/components/post/Comment/CommentListItem/CommentEditForm.tsx
  src/components/post/Comment/CommentSection.tsx
  src/components/post/Comment/useCommentList.ts
  src/lib/api/comment.ts
  src/stores/useCommentLoadingStore.ts
  src/stores/useCommentReply.ts
  src/utils/comment.tsx
  src/utils/date.ts
Labels: 🌟 feat

#73 Feat/combine-component 컴포넌트 교체, 즐겨찾기리스트 조회, 장소 상세 조회 API 연결
  src/app/map/page.tsx
  src/components/map/BookmarkInfo.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceCard.tsx
  src/components/map/PlaceModal.tsx
  src/components/map/PlaceUserMemos.tsx
  src/components/map/PlaceUserMemosHeader.tsx
  src/components/map/UserMemoCard.tsx
  src/components/map/UserMemoCards.tsx
  src/lib/api/map.ts
  src/types/map.ts
Labels: 🌟 feat, 🎨 UI

#84 계정정보 페이지 생성 및 기본정보 섹션 UI
  src/app/setting/page.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.client.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/Setting/ProfileInfoSection.tsx
  src/components/Setting/SettingComponent.tsx
  src/components/common/Input/BaseInput.tsx
  src/components/layout/Header/Header.tsx
  src/lib/fetch/client.ts
Labels: 🎨 UI

#87 UI/user-group-list 유저 그룹 리스트 UI, API 연결, Zustand 적용
  src/app/map/page.tsx
  src/components/layout/Footer/Footer.tsx
  src/components/map/BookmarkInfo.tsx
  src/components/map/PlaceCard.tsx
  src/components/map/PlaceModal.tsx
  src/components/map/PlaceUserMemos.tsx
  src/components/map/PlaceUserMemosHeader.tsx
  src/components/map/SideMenu.tsx
  src/components/map/UserGroupList.tsx
  src/components/map/UserMemoCard.tsx
  src/components/map/UserMemoCards.tsx
  src/lib/api/map.ts
  src/stores/mapStore.ts
  src/types/map.ts
Labels: 🌟 feat, 🎨 UI

#92 UI/map-favorite 즐겨찾기 추가 모달 UI 및 장소의 즐겨찾기 상태 API연결
  src/app/map/page.tsx
  src/components/map/FavoriteAddModal.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceModal.tsx
  src/components/map/PlaceUserMemos.tsx
  src/components/map/PlaceUserMemosHeader.tsx
  src/components/map/SideMenu.tsx
  src/components/map/UserGroupList.tsx
  src/lib/api/map.ts
  src/stores/mapStore.ts
Labels: 🎨 UI

#94 로그아웃 UI 구현 및 API 연결
  src/app/api/auth/signout/route.ts
  src/components/common/SidebarButton/SidebarButton.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/lib/api/auth.ts
Labels: 🌟 feat

#98 회원 탈퇴, 로그아웃 토스트 적용
  src/components/Setting/SettingComponent.tsx
  src/components/layout/Sidebar/Sidebar.tsx
Labels: 🐛 bug

#97 Feat/user-like-list 유저의 그룹에 대한 즐겨찾기 조회 UI, API 연결
  src/app/map/page.tsx
  src/components/map/FavoriteCard.tsx
  src/components/map/FavoriteList.tsx
  src/components/map/GroupCard.tsx
  src/components/map/GroupCardList.tsx
  src/components/map/GroupsFavoriteList.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceModal.tsx
  src/components/map/PlaceUserMemos.tsx
  src/components/map/PlaceUserMemosHeader.tsx
  src/components/map/UserGroupList.tsx
  src/components/map/UserMemoCard.tsx
  src/lib/api/map.ts
  src/stores/mapStore.ts
  src/types/map.ts
  src/utils/date.ts
Labels: 🌟 feat, 🎨 UI

#99 프로필 변경 API연결
  src/components/Setting/ProfileInfoSection.tsx
  src/components/Setting/useProfileInfoSection.ts
  src/components/common/Input/DateInput.tsx
  src/lib/api/profile.ts
  src/utils/date.ts
Labels: 🌟 feat

#102 신고 페이지 생성
  src/app/report/[reportId]/page.tsx
  src/components/Report/ReportComponent.tsx
  src/components/Report/ReportSelector.tsx
  src/components/Report/useReportComponent.ts
  src/components/layout/Header/Header.tsx
  src/components/post/Comment/useCommentList.ts
  src/lib/api/report.ts
  src/types/report.ts
  src/utils/date.ts
Labels: 🎨 UI

#105 빌드 오류 수정
  src/components/Report/useReportComponent.ts
Labels: 🐛 bug

#115 프로필 작성한 댓글 UI 및 프로필 미로그인 상태 예외처리 추가
  src/app/profile/[userId]/page.tsx
  src/components/Favorite/FavoriteGroupList.tsx
  src/components/Profile/ProfileCommentCard.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.client.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/Profile/ProfilePostList.tsx
  src/components/Profile/ProfileTab/ProfileTabs.tsx
  src/components/common/ErrorBoundary/ErrorBoundary.tsx
  src/hooks/useProfileItemList.ts
  src/lib/api/profile.ts
  src/types/post.ts
Labels: 🌟 feat, 🎨 UI

#114 게시글 수정 기능 구현과 관련된 파일 정리 및 신고 기능 연결
  src/app/board/[category]/[postId]/page.tsx
  src/components/editor/PostEditor.tsx
  src/components/post/PostAuthor.tsx
  src/components/post/PostFooter.tsx
  src/components/post/PostHeader.tsx
  src/hooks/editor/useEditorInit.ts
  src/hooks/editor/usePostSubmitHandler.ts
  src/hooks/useRestoreDraft.ts
  src/lib/api/post.client.ts
  src/lib/api/post.server.ts
  src/lib/api/post.ts
  src/lib/api/posts.ts
  src/types/editor.ts
Labels: 🌟 feat, ♻️ refactor

#122 디데이 계산 로직 추가
  next.config.ts
  src/app/board/[category]/[postId]/page.tsx
  src/components/Favorite/FavoriteHeader.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/map/GroupsFavoriteList.tsx
  src/components/map/UserGroupList.tsx
  src/lib/api/post.server.ts
  src/types/post.ts
  src/utils/date.ts
Labels: ♻️ refactor

#119 Feat/markerinfo 지도 검색 기능, 마커 모달, 위치 이동 구현
  public/marker/favoriteMarker.svg
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceCard.tsx
  src/components/map/PlaceModal.tsx
  src/stores/mapStore.ts
  src/types/map.ts
  src/utils/mapUtil.ts
Labels: 🌟 feat, 🎨 UI

#118 Feat/popular list: 인기게시글 구현
  .gitignore
  public/icons/populardown.svg
  public/icons/popularup.svg
  src/components/Home/HomeComponent.tsx
  src/components/Home/PopularPostList.tsx
  src/components/common/Icons/index.tsx
  src/lib/api/popular.ts
Labels: 🌟 feat

#126 Fix/sse notification : SSE인증 header기반으로 ref(버그 해결), 연결 유지를 위한 ping 처리, 비로그인상태에서 알림렌더링 제거, 조건부 썸네일 렌더링
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/layout/Header/Header.tsx
  src/components/notification/NotificationItem.tsx
  src/hooks/useSse.ts
  src/lib/api/notification.ts
  src/stores/useAuthStore.ts
  src/types/event-source-polyfill.d.ts
Labels: 🐛 bug, ♻️ refactor

#128 CSP 방어코드 제거
  next.config.ts
Labels: 🐛 bug

#135 fix: 카카오 지도 로드 오류 수정
  middleware.ts
  public/init-kakao.js
  src/app/layout.tsx
Labels: 🐛 bug

#131 홈 화면 핫플레이스 지도와 리스트 추가
  package-lock.json
  src/components/Home/HomeComponent.tsx
  src/components/Home/HomeSectionMapCard.tsx
  src/components/Home/Map/ExploreButton.tsx
  src/components/Home/Map/HotPlaceHeader.tsx
  src/components/Home/Map/HotPlaceList.tsx
  src/components/Home/Map/MapBox.tsx
Labels: 🎨 UI

#137 버그 및 개선사항 적용
  public/icons/map.svg
  src/app/board/[category]/[postId]/PostPageClient.tsx
  src/app/board/[category]/[postId]/page.tsx
  src/components/Home/Map/HotPlaceHeader.tsx
  src/components/Home/Map/MapBox.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/common/Icons/index.tsx
  src/components/common/SidebarButton/SidebarButtonList.tsx
  src/components/post/Comment/CommentInput.tsx
  src/components/post/Comment/CommentList.tsx
  src/components/post/Comment/CommentListItem/index.tsx
  src/components/post/Comment/CommentSection.tsx
  src/components/post/Comment/useCommentList.ts
  src/components/post/PostAuthor.tsx
  src/components/post/PostFooterInteraction.tsx
  src/lib/api/comment.ts
  src/types/comment.ts
  src/utils/date.ts
Labels: 🐛 bug, 🌟 feat

#138 홈 화면 핫플레이스 거리 표시와 거리 순 정렬 추가 및 버그 수정
  src/components/Home/Map/HotPlaceHeader.tsx
  src/components/Home/Map/HotPlaceList.tsx
  src/utils/mapUtil.ts
Labels: 🐛 bug, 🎨 UI

#148 fix/kakao-sse : 카카오로그인 시 sse 401 해결
  src/components/auth/LoginForm/useLoginForm.ts
Labels: 🐛 bug

#145 Ref/clickable 리팩토링 이슈 해결
  public/marker/cafe_star.svg
  public/marker/others_star.svg
  public/marker/restaurant_star.svg
  public/marker/shop_star.svg
  src/components/map/BookmarkInfo.tsx
  src/components/map/FavoriteAddModal.tsx
  src/components/map/FavoriteCard.tsx
  src/components/map/GroupCard.tsx
  src/components/map/GroupsFavoriteList.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceCard.tsx
  src/components/map/PlaceModal.tsx
  src/components/map/PlaceUserMemosHeader.tsx
  src/components/map/SideMenu.tsx
  src/components/map/UserGroupList.tsx
  src/components/map/UserMemoCard.tsx
  src/utils/mapUtil.ts
Labels: ♻️ refactor

#151 Ref/map-store map관련 Zustand 상태변수, 메서드 분리
  src/app/map/page.tsx
  src/components/Home/Map/HotPlaceList.tsx
  src/components/Home/Map/MapBox.tsx
  src/components/map/BookmarkInfo.tsx
  src/components/map/FavoriteAddModal.tsx
  src/components/map/FavoriteCard.tsx
  src/components/map/FavoriteList.tsx
  src/components/map/GroupCard.tsx
  src/components/map/GroupCardList.tsx
  src/components/map/GroupsFavoriteList.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceCard.tsx
  src/components/map/PlaceModal.tsx
  src/components/map/PlaceUserMemos.tsx
  src/components/map/PlaceUserMemosHeader.tsx
  src/components/map/SideMenu.tsx
  src/components/map/UserGroupList.tsx
  src/components/map/UserMemoCard.tsx
  src/components/map/UserMemoCards.tsx
  src/stores/map/useMapFavoriteStore.ts
  src/stores/map/useMapGroupStore.ts
  src/stores/map/useMapPageStore.ts
  src/stores/map/useMapPlaceStore.ts
  src/stores/map/useMapStore.ts
  src/stores/mapStore.ts
Labels: ♻️ refactor

#152 Bug/prevdata-load map페이지 컴포넌트에 이전 데이터 남아있다가 전환되는 문제 수정
  src/components/map/GroupsFavoriteList.tsx
  src/components/map/PlaceUserMemosHeader.tsx
  src/components/map/UserGroupList.tsx
  src/stores/map/useMapFavoriteStore.ts
  src/stores/map/useMapGroupStore.ts
  src/stores/map/useMapPlaceStore.ts
Labels: ♻️ refactor

#156 프로필 없을 경우 예외처리 및 팔로우버튼 추가
  src/app/profile/[userId]/loading.tsx
  src/app/profile/[userId]/not-found.tsx
  src/app/profile/[userId]/page.tsx
  src/components/AuthInitializer.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/Profile/ProfilePostList.tsx
  src/components/Profile/ProfileTab/ProfileTabContent.tsx
  src/components/post/PostAuthor.tsx
  src/hooks/useProfileItemList.ts
  src/lib/api/profile.ts
  src/types/profile.ts
Labels: 🌟 feat

#158 핫플레이스 관련 버그 수정과 리팩토링, 프로필 즐겨찾기 관련 낙관적 업데이트 적용
  src/app/favorite/[groupId]/FavoritePageClient.tsx
  src/components/Favorite/FavoriteGroupList.tsx
  src/components/Home/HomeSectionMapCard.tsx
  src/components/Home/Map/HotPlaceHeader.tsx
  src/components/Home/Map/HotPlaceList.tsx
  src/components/Home/Map/MapBox.tsx
  src/hooks/useClickOutside.ts
  src/hooks/useHotPlace.ts
  src/hooks/useRestoreDraft.ts
  src/types/map.ts
Labels: 🐛 bug, ♻️ refactor

#161 팔로우 관련 버그 수정
  src/components/Profile/Modal/UserFollowItem.tsx
  src/components/layout/Footer/Footer.tsx
  src/lib/api/follow.ts
Labels: 🐛 bug

#163 fix/sse : useLoginForm에서의 토큰 전역저장 코드 복구
  src/components/auth/LoginForm/useLoginForm.ts
Labels: 🐛 bug

#165 즐겨찾기 그룹 조회 버그 수정과 카카오톡 공유하기 기능 구현 및 사용자 UX 개선
  src/app/profile/[userId]/page.tsx
  src/components/Favorite/FavoriteGroupCard.tsx
  src/components/Favorite/FavoriteGroupList.tsx
  src/components/Favorite/FavoriteItemCard.tsx
  src/components/Home/Map/HotPlaceList.tsx
  src/components/Profile/ProfileTab/ProfileTabClient.tsx
  src/components/Profile/ProfileTab/ProfileTabContent.tsx
  src/components/editor/EditorActions.tsx
  src/components/post/PostFooter.tsx
  src/components/post/ShareModal.tsx
  src/hooks/useFavorite.ts
  src/hooks/useKakaoInit.ts
  src/types/kakao.d.ts
  src/utils/shareToKakao.ts
Labels: 🐛 bug, 🌟 feat

#164 Feat/post: 인기게시글 수정
  package-lock.json
  package.json
  src/components/Home/PopularPostList.tsx
  src/lib/api/popular.ts
Labels: 🌟 feat

#169 유저 근처 정보 받아올 때 access token 보내지 않도록 수정
  src/lib/api/map.ts
Labels: 🌟 feat

#174 bug : 검색 결과 모달 위치 수정
  src/components/map/KakaoMap.tsx
Labels: 🐛 bug

#173 데이터 추가 중 버그 수정
  src/components/Favorite/FavoriteHeader.tsx
  src/components/Home/HomeSectionCard.tsx
  src/components/Home/HomeSectionImageItem.tsx
  src/components/Profile/Modal/UserFollowItem.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/Setting/ProfileImageUploader.tsx
  src/components/common/SectionCards/PostImageCard.tsx
  src/components/common/SectionCards/PostListCard.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderSkeleton.tsx
  src/components/map/BookmarkInfo.tsx
  src/components/map/GroupsFavoriteList.tsx
  src/components/map/SideMenu.tsx
  src/components/map/UserGroupList.tsx
  src/components/post/Comment/CommentListItem/index.tsx
  src/components/post/PostAuthor.tsx
Labels: 🐛 bug

#176 Ref/del-serach-sample 검색어 예시 삭제
  src/components/map/KakaoMap.tsx
Labels: ♻️ refactor

#177 style/noti-modal : 알림모달 모바일 비율, 위치 맞춤 적용
  src/components/notification/NotificationModal.tsx
Labels: 🐛 bug

#179 ref/model : 유저 메모 이미지+이름+메모 배치구조 개선
  src/components/map/UserMemoCard.tsx
Labels: 🐛 bug

#181 페이지네이션 오류 수정
  src/app/board/[category]/page.tsx
Labels: 🐛 bug

#182 Update README.md
  README.md
Labels: 📝 docs
