Repository code-is-evenly-cooked/even-zaro-front, pull requests merged in 2025-05, with the labels that each got.

#1 ESLint, Prettier, Pretendard 폰트 설정 파일 추가
  .prettierrc
  .vscode/settings.json
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/layout/Layout.tsx
  tailwind.config.js
Labels: 🌟 feat

#2 이슈 및 pr 템플릿 추가
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/ISSUE_TEMPLATE/troubleshotting.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#3 파비콘, 메타데이터, 공통 파일 추가
  eslint.config.mjs
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/utils/decodeJwt.ts
  src/utils/validate.ts
  tailwind.config.js
Labels: 🎨 UI

#4 공통 버튼, TextField Component 추가
  public/icons/eyeClose.svg
  public/icons/eyeOpen.svg
  public/icons/kakao.svg
  src/components/common/Button/BaseButton.tsx
  src/components/common/Button/IconButton.tsx
  src/components/common/Button/styles.ts
  src/components/common/Icons/index.tsx
  src/components/common/Input/BaseInput.tsx
  src/components/common/Input/PasswordInput.tsx
  src/components/common/Input/TextInput.tsx
  src/components/common/LoadingSpinner/LoadingSpinner.tsx
  src/types/button.ts
  src/types/input.ts
  tailwind.config.js
Labels: 🌟 feat, 🎨 UI

#5 회원가입 UI, 약관 페이지, 공통 모달 추가
  package-lock.json
  package.json
  public/icons/close.svg
  public/icons/logoIcon.svg
  public/terms/privacy-policy.md
  public/terms/terms-of-service.md
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/signup/page.tsx
  src/components/auth/Signup/SignupForm.tsx
  src/components/auth/Signup/useSignupForm.ts
  src/components/common/Agreement/AgreementItem.tsx
  src/components/common/Agreement/AgreementList.tsx
  src/components/common/Button/styles.ts
  src/components/common/Icons/index.tsx
  src/components/common/Input/BaseInput.tsx
  src/components/common/Modal/BaseModal.tsx
  src/components/common/Modal/ModalOverlay.tsx
  src/components/common/Modal/ModalPortal.tsx
  src/components/support/TermsModal.tsx
  src/hooks/useModal.ts
  src/types/button.ts
  src/types/modal.d.ts
  src/utils/decodeJwt.ts
  tailwind.config.js
Labels: 🌟 feat, 🎨 UI

#6 로그인UI 및 카카오 로그인 연결
  .env.example
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/auth/LoginForm/LoginForm.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/auth/Signup/KakaoLoginButton.tsx
  src/components/common/Button/IconButton.tsx
  src/providers/Providers.tsx
  src/types/agreement.d.ts
  src/types/next-auth.d.ts
Labels: 🌟 feat, 🎨 UI

#7 비밀번호 재설정 이메일 전송화면, 비밀번호 재설정UI 추가
  .npmrc
  src/app/password-forget/page.tsx
  src/app/password-reset/PasswordResetPageClient.tsx
  src/app/password-reset/page.tsx
  src/components/auth/LoginForm/LoginForm.tsx
  src/components/auth/PasswordForget/PasswordForgetForm.tsx
  src/components/auth/PasswordForget/usePasswordForgetForm.ts
  src/components/auth/PasswordReset/PasswordResetForm.tsx
  src/components/auth/PasswordReset/usePasswordResetForm.ts
Labels: 🌟 feat, 🎨 UI

#8 이메일 인증 UI 추가
  src/app/email-validation/page.tsx
  src/app/password-reset/PasswordResetPageClient.tsx
  src/app/password-reset/page.tsx
  src/components/auth/EmailValidation/EmailValidationForm.tsx
  src/components/auth/Signup/useSignupForm.ts
  src/components/common/Input/PasswordInput.tsx
Labels: 🌟 feat, 🎨 UI

#9 글 작성 페이지와 에디터의 레이아웃과 기본 설정, indexedDB 기반의 임시 저장 기능 구현
  src/app/editor/EditorPageClient.tsx
  src/app/editor/page.tsx
  src/app/globals.css
  src/components/editor/PostEditor.tsx
  src/stores/usePostStore.ts
  src/utils/editorStorage.ts
Labels: 🌟 feat, 🎨 UI

#10 홈화면 헤더 및 사이드바 베이스 추가
  package-lock.json
  package.json
  public/icons/homeIcon.svg
  public/icons/notificationIcon.svg
  public/icons/rightArrow.svg
  public/icons/searchIcon.svg
  src/app/layout.tsx
  src/components/Dropdown/CategoryDropdown.tsx
  src/components/Searchbar/Searchbar.tsx
  src/components/Searchbar/useSearchbar.ts
  src/components/common/Button/styles.ts
  src/components/common/Icons/index.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar/Sidebar.tsx
  src/constants/categories.ts
  src/layout/Layout.tsx
Labels: 🎨 UI

#11 이메일 회원가입 및 로그인 API연결
  .env.example
  src/app/api/auth/signin/route.ts
  src/app/api/auth/signup/route.ts
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/auth/Signup/useSignupForm.ts
  src/components/layout/Layout.tsx
  src/lib/api/auth.ts
  src/lib/auth/cookie.ts
  src/lib/response.ts
  src/types/auth.d.ts
Labels: 🌟 feat

#12 Toast UI 추가
  src/app/layout.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/auth/Signup/useSignupForm.ts
  src/components/common/Input/PasswordInput.tsx
  src/components/common/ToastMessage/ToastMessageContainer.tsx
  src/components/common/ToastMessage/ToastMessageItem.tsx
  src/components/common/ToastMessage/index.ts
  src/providers/Providers.tsx
  src/providers/ToastMessageProvider.tsx
  src/types/toastMessage.d.ts
  tailwind.config.js
Labels: 🌟 feat

#14 글쓰기 에디터 한글화와 카테고리 드롭다운과 태그 구현 및 상태 관리 기능 추가
  src/app/globals.css
  src/components/editor/PostEditor.tsx
  src/hooks/useAutoSaveDraft.ts
  src/hooks/useEditorImageUpload.ts
  src/lib/api/posts.ts
  src/stores/usePostStore.ts
  src/types/toast-ui-editor.d.ts
  src/utils/editorStorage.ts
Labels: 🌟 feat, ♻️ refactor, 🎨 UI

#15 유저 정보 최신화 및 token refresh api현결
  src/app/api/auth/refresh/route.ts
  src/app/api/users/my/route.ts
  src/components/AuthInitializer.tsx
  src/lib/fetch/fetchWithAuth.client.ts
  src/lib/fetch/fetchWithAuth.ts
  src/providers/Providers.tsx
  src/stores/useAuthStore.ts
  src/types/api.ts
Labels: 🌟 feat

#16 비밀번호 재설정 이메일 API 연결
  package-lock.json
  package.json
  src/app/api/auth/signin/password-forget/route.ts
  src/components/auth/PasswordForget/usePasswordForgetForm.ts
  src/lib/api/auth.ts
Labels: 🌟 feat

#17 글 작성 API 연결, 이미지 리스트와 썸네일 추출 기능 구현
  src/components/editor/PostEditor.tsx
  src/hooks/useEditorImageUpload.ts
  src/lib/api/auth.ts
  src/lib/api/posts.ts
  src/utils/editorImage.ts
Labels: 🌟 feat

#19 비밀번호 재설정 API 연결
  src/app/api/auth/signin/password-reset/route.ts
  src/app/layout.tsx
  src/components/auth/PasswordReset/usePasswordResetForm.ts
  src/lib/api/auth.ts
  src/providers/Providers.tsx
  src/stores/usePostStore.ts
  src/utils/editorStorage.ts
Labels: 🐛 bug, 🌟 feat

#20 비밀번호 재설정 오탈자 수정
  src/lib/api/auth.ts
Labels: 🐛 bug

#21 API 호출 공통 로직 개선 및 카카오 로그인 적용
  src/app/api/auth/signin/social/route.ts
  src/components/AuthInitializer.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/lib/fetch/client.ts
  src/lib/fetch/fetchWithAuth.client.ts
  src/providers/Providers.tsx
  src/types/api.ts
Labels: 🌟 feat

#23 accessToken, refreshToken없을 경우 무한 호출 이슈 수정
  src/app/api/auth/refresh/route.ts
  src/app/api/users/my/route.ts
  src/lib/fetch/client.ts
Labels: 🐛 bug

#22 임시 고정 중이던 카테고리와 태그 드롭 다운 연동 및 토스트 팝업 적용, 임시 저장 불러오기 여부 확인 추가
  src/components/editor/PostEditor.tsx
  src/components/editor/RestoreDraftModal.tsx
  src/hooks/useRestoreDraft.ts
  src/types/editor.ts
  src/utils/editorStorage.ts
Labels: 🐛 bug, 🌟 feat

#24 사이드바 버튼 추가 및 액션 연결
  public/icons/home.svg
  public/icons/logoWhite.svg
  public/icons/shoppingBag.svg
  public/icons/tip.svg
  public/icons/together.svg
  src/app/layout.tsx
  src/components/common/Icons/index.tsx
  src/components/common/SidebarButton/SidebarButton.tsx
  src/components/common/SidebarButton/SidebarButtonList.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Sidebar/Sidebar.tsx
Labels: 🌟 feat, 🎨 UI

#25 로그인 사용자일 경우 헤더에 프로필 이미지 표시
  next.config.ts
  package-lock.json
  package.json
  public/icons/defaultProfile.svg
  src/components/AuthInitializer.tsx
  src/components/auth/LoginForm/useLoginForm.ts
  src/components/common/Icons/index.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/HeaderShell.tsx
  src/components/layout/Layout.tsx
  src/lib/api/auth.ts
  src/providers/Providers.tsx
  src/providers/ReactQueryProvider.tsx
  src/stores/useAuthStore.ts
Labels: 🌟 feat

#26 홈화면 공통 헤더, 리스트 형식 공통 컴포넌트 UI 생성
  src/app/page.tsx
  src/components/Home/HomeComponent.tsx
  src/components/Home/HomeSectionCard.tsx
  src/components/Home/HomeSectionHeader.tsx
  src/components/Home/HomeSectionListItem.tsx
  src/components/Home/SectionType.tsx
  src/components/layout/Layout.tsx
Labels: 🌟 feat, 🎨 UI

#27 게시글 상세 페이지 폴더 구조와 기본 UI 구현 및 API 연결
  src/app/board/[category]/[postId]/page.tsx
  src/app/board/[category]/page.tsx
  src/components/post/PostAuthor.tsx
  src/components/post/PostContent.tsx
  src/components/post/PostHeader.tsx
  src/lib/api/post.ts
Labels: 🌟 feat, 🎨 UI

#30 같이쓰자, 자취일상 리스트 컴포넌트 추가
  package-lock.json
  package.json
  public/icons/placeholderImage.svg
  src/app/board/[category]/page.tsx
  src/components/Dropdown/MainCategoryDropdown.tsx
  src/components/Home/HomeSectionHeader.tsx
  src/components/Home/SectionType.tsx
  src/components/PostList/PostListComponent.tsx
  src/components/PostList/PostListHeader.tsx
  src/components/PostList/SubCategoryFilter.tsx
  src/components/Searchbar/Searchbar.tsx
  src/components/common/SectionCards/PostListCard.tsx
  src/components/layout/Header/Header.tsx
  src/components/layout/Header/HeaderShell.tsx
  src/components/layout/Header/HeaderSkeleton.tsx
  src/components/layout/HeaderShell.tsx
  src/components/layout/Layout.tsx
  src/constants/category.tsx
  src/types/category.ts
  src/types/post.ts
  src/utils/category.ts
  src/utils/date.ts
Labels: 🌟 feat, 🎨 UI

#31 이미지 키 값 네이밍 변경
  .env.example
  src/app/board/[category]/[postId]/page.tsx
  src/app/board/[category]/page.tsx
  src/components/Home/HomeComponent.tsx
  src/components/Home/HomeSectionCard.tsx
  src/components/common/SectionCards/PostImageCard.tsx
  src/components/common/SectionCards/PostListCard.tsx
  src/components/editor/PostEditor.tsx
  src/components/layout/Header/Header.tsx
  src/components/post/PostAuthor.tsx
  src/lib/api/posts.ts
  src/stores/useAuthStore.ts
  src/stores/usePostStore.ts
  src/types/post.ts
Labels: ♻️ refactor

#35 API fetch 유틸 함수 리팩토링 및 홈, 리스트 api 연결
  src/app/board/[category]/page.tsx
  src/app/page.tsx
  src/components/Home/HomeComponent.tsx
  src/components/Home/HomeSectionCard.tsx
  src/components/Home/HomeSectionListItem.tsx
  src/components/PostList/PostListComponent.tsx
  src/components/common/Fallback/FallbackMessage.tsx
  src/components/common/SectionCards/PostImageCard.tsx
  src/components/common/SectionCards/PostListCard.tsx
  src/lib/adapters/normalizePost.ts
  src/lib/api/posts.ts
  src/lib/fetch/buildHeaders.ts
  src/lib/fetch/client.ts
  src/lib/fetch/fetchWithAuth.ts
  src/lib/fetch/parseError.ts
  src/lib/fetch/refresh/client.ts
  src/lib/fetch/refresh/server.ts
  src/lib/fetch/server.ts
  src/lib/fetch/util/objectToQueryString.ts
  src/types/post.ts
  src/utils/image.ts
Labels: 🌟 feat

#36 게시글 상세 페이지에 디데이, 카테고리와 태그, 본문 푸터 플로팅을 추가하고 프리사인드 url을 key 값으로 구성할 수 있게 수정
  src/app/board/[category]/[postId]/page.tsx
  src/components/layout/Layout.tsx
  src/components/post/PostAuthor.tsx
  src/components/post/PostContent.tsx
  src/components/post/PostFooter.tsx
  src/components/post/PostFooterWithFloating.tsx
  src/components/post/PostHeader.tsx
  src/hooks/useEditorImageUpload.ts
  src/lib/api/post.client.ts
  src/lib/api/post.ts
  src/lib/api/posts.ts
Labels: 🌟 feat, ♻️ refactor, 🎨 UI

#40 저장 누락 파일 추가
  src/components/common/SectionCards/PostListCard.tsx
  src/utils/image.ts
Labels: 🐛 bug

#43 중간 점검 에디터 페이지 관련 버그와 논의사항 수정
  src/app/editor/page.tsx
  src/app/globals.css
  src/components/editor/PostEditor.tsx
  src/components/layout/Footer/Footer.tsx
  src/hooks/useEditorScrollLock.ts
  src/lib/api/posts.ts
  src/utils/editorImage.ts
Labels: 🐛 bug

#44 중간 점검 버그 수정
  public/icons/eyeClose.svg
  public/icons/eyeOpen.svg
  src/components/PostList/PostListResult.tsx
  src/components/common/Icons/index.tsx
  src/components/common/Input/PasswordInput.tsx
  src/components/common/SectionCards/PostImageCard.tsx
  src/components/common/SectionCards/PostListCard.tsx
  src/components/common/SidebarButton/SidebarButton.tsx
  src/components/common/SidebarButton/SidebarButtonList.tsx
  src/components/layout/Header/Header.tsx
  src/constants/category.tsx
  src/types/post.ts
Labels: 🐛 bug

#39 Feat/map 카카오지도 API 연동, 좌측상단 메뉴바 UI
  .env.example
  src/app/api/auth/[...nextauth]/route.ts
  src/app/map/page.tsx
  src/components/common/Icons/index.tsx
  src/components/layout/Header/Header.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/SideMenu.tsx
Labels: 🎨 UI

#47 Feat/sse notification : 로그인 유저 대상 SSE 연결 (header에서 useSse 훅 호출)
  src/components/layout/Header/Header.tsx
  src/hooks/useSse.ts
Labels: 🌟 feat

#48 임시 저장 불러오기 전 이미 에디터에 표시되는 버그 수정 및 임시 저장 시 카테고리와 태그 제거
  src/components/editor/PostEditor.tsx
  src/hooks/useAutoSaveDraft.ts
  src/hooks/useRestoreDraft.ts
  src/types/editor.ts
  src/utils/editorStorage.ts
Labels: 🐛 bug

#52 UI/place-list-modal 지도 페이지 좌측 하단 인근 장소 리스트 컴포넌트 UI
  public/placeCategory/cafe.svg
  public/placeCategory/etc.svg
  public/placeCategory/food.svg
  public/placeCategory/heart.svg
  public/placeCategory/market.svg
  src/components/common/Icons/category.tsx
  src/components/map/KakaoMap.tsx
  src/components/map/PlaceCard.tsx
  src/components/map/PlaceModal.tsx
  src/components/map/SideMenu.tsx
Labels: 🎨 UI

#55 Feat/notification : 알림모달 컴포넌트 ui, 헤더 알림버튼 누를 시 토글
  src/components/layout/Header/Header.tsx
  src/components/notification/NotificationHeader.tsx
  src/components/notification/NotificationItem.tsx
  src/components/notification/NotificationModal.tsx
Labels: 🎨 UI

#56 프로필 페이지 전체 레이아웃과 즐겨찾기 그룹까지 UI 구현 및 게시글 조회 500 오류 해결
  public/icons/setting.svg
  public/icons/share.svg
  src/app/board/[category]/[postId]/PostPageClient.tsx
  src/app/board/[category]/[postId]/page.tsx
  src/app/editor/EditorPageClient.tsx
  src/app/profile/page.tsx
  src/components/Profile/BookmarkGroup.tsx
  src/components/Profile/BookmarkList.tsx
  src/components/Profile/ProfileHeader.tsx
  src/components/Profile/ProfileTabContent.tsx
  src/components/Profile/ProfileTabs.tsx
  src/components/common/AuthGuard/AuthGuard.tsx
  src/components/common/Icons/index.tsx
  src/components/post/PostContent.tsx
  src/components/post/PostFooter.tsx
  src/hooks/useProfile.ts
  src/lib/api/post.ts
  src/stores/useAuthStore.ts
  src/types/profile.ts
Labels: 🐛 bug, 🎨 UI

#57 #56 PR과 관련된 리뷰 사항 수정 반영
  src/app/board/[category]/[postId]/page.tsx
  src/components/Profile/BookmarkGroup.tsx
  src/components/Profile/ProfileHeader.tsx
  src/components/Profile/ProfileTabs.tsx
  src/components/post/PostFooter.tsx
  src/hooks/useProfile.ts
  src/types/profile.ts
Labels: 🐛 bug, ♻️ refactor
